# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignUpExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignUpExample
  pod 'VizAISDK'
  target 'SignUpExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SignUpExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
